---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: clojure
    tag: alpine

inputs:
- name: git-repo

# this should fail becaluse of no db
run:
  path: sh
  args:
  - -xuec
  - |
    cd git-repo
    lein cloverage
